version: 2

updates:
  - package-ecosystem: "nix"
    open-pull-requests-limit: 3
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      nix-deps:
        patterns:
          - "*"