[bar]
order = [ "default", "workspaces" ]

    [bar.default]
    auto_hide = true
    background_opacity = 0.69999999999999996
    center = [ "clock" ]
    contact_shadow = true
    end = [ "keyboard_layout", "tray", "recorder", "network", "bluetooth", "volume", "battery", "notifications" ]
    layer = "top"
    margin_edge = 4
    position = "bottom"
    radius = 10
    reserve_space = false
    shadow = true
    show_on_workspace_switch = false
    start = [ "cpu", "ram", "temp", "taskbar" ]
    widget_spacing = 8

        [bar.default.dead_zone]
        command = "noctalia msg panel-toggle control-center"
        right_command = "noctalia msg panel-toggle session"

    [bar.workspaces]
    auto_hide = true
    background_opacity = 0.59999998658895493
    center = [ "workspaces" ]
    enabled = true
    end = []
    margin_edge = 6
    margin_ends = 300
    position = "left"
    reserve_space = false
    start = []

[control_center]
hidden_tabs = []
sidebar = "compact"
sidebar_section = "compact"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "mic_mute"

[desktop_widgets]
schema_version = 1
widget_order = [ "desktop-widget-0000000000000002", "desktop-widget-0000000000000001", "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 144.0
    box_width = 256.0
    cx = 720.0
    cy = 661.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        color = "primary"
        format = "{:%H:%M}"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 224.0
    box_width = 1440.0
    cx = 720.0
    cy = 112.0
    flip_y = true
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        bands = 96.0
        centered = false
        color_2 = "primary"
        mirrored = true
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 720.0
    cy = 736.5
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = false
        color = "primary"
        format = "{: %d %b, %A}"

[dock]
active_monitor_only = true
auto_hide = true
enabled = false
launcher_position = "start"
position = "bottom"

[idle]
behavior_order = [ "lock", "screen-off" ]

    [idle.behavior.idle-behavior]
    action = "screen_off"
    enabled = true
    timeout = 900

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.0
blurred_desktop = false
tint_intensity = 0.0

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 64.0
    box_width = 400.0
    cx = 720.0
    cy = 690.4296875
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 192.0
    box_width = 320.0
    cx = 720.0
    cy = 229.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        color = "primary"
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 368.0
    box_width = 1440.0
    cx = 720.0
    cy = 0.0
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        bands = 68.0
        show_when_idle = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 80.0
    box_width = 560.0
    cx = 720.0
    cy = 309.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        color = "primary"
        format = "{:%d %b, %A}"
        shadow = true

[notification]
offset_y = 20
position = "bottom_right"
scale = 1.1000000089406967

[osd]
offset_y = 56
position = "bottom_center"
scale = 1.4000000134110451

    [osd.kinds]
    media = false

[plugin_settings."noctalia/notes"]
notes_dir = "~/notes"

[plugins]
enabled = [ "noctalia/screen_recorder", "noctalia/wallhaven", "noctalia/timer", "noctalia/translator" ]

    [[plugins.source]]
    auto_update = true
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    auto_update = true
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
clipboard_confirm_clear_history = true
clipboard_history_max_entries = 1000
clipboard_image_action_command = "satty -f -"
launch_apps_as_systemd_services = true
offline_mode = false
password_style = "random"
polkit_agent = false
settings_show_advanced = true
telemetry_enabled = false

    [shell.launcher]
    app_grid = false
    compact = false
    session_search = true

    [shell.panel]
    borders = false
    clipboard_placement = "attached"
    launcher_placement = "attached"
    open_near_click_control_center = true
    shadow = true
    transparency_mode = "soft"

    [shell.screenshot]
    directory = "/home/alex/Pictures/Screenshots"
    pipe_command = "satty -f -"
    pipe_to_command = true
    save_to_file = true

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "q"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    enabled = true
    shortcut = "e"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "s"
    variant = "destructive"

[theme]
builtin = "Tokyo-Night"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "faithful"

[wallpaper]
directory = "/home/alex/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/alex/Pictures/Wallpapers/wallhaven_n65epw.jpg"

    [wallpaper.last]
    path = "/home/alex/Pictures/Wallpapers/wallhaven_n65epw.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/alex/Pictures/Wallpapers/wallhaven_n65epw.jpg"

[widget.audio_visualizer]
bands = 30
scale = 1.5
width = 400.0

[widget.battery]
show_label = false

[widget.control-center]
glyph = "rosette-filled"

[widget.cpu]
show_label = false

[widget.keyboard_layout]
show_icon = false

[widget.media]
art_size = 17.0
hide_when_no_media = true
title_scroll = "always"

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.network]
show_label = false

[widget.notes]
type = "noctalia/notes:notes"

[widget.ram]
show_label = false

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.temp]
show_label = false

[widget.tray]
drawer = true
match_adjacent_spacing = true
pinned = [ "AmneziaVPN", "Discord", "steam", "TelegramDesktop" ]

[widget.volume]
show_label = false

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.workspaces]
minimal = false