config_version = 2

[bar]
order = [ "default", "workspaces" ]

    [bar.default]
    auto_hide = false
    background_opacity = 0.69999999999999996
    center = [ "taskbar", "clock" ]
    contact_shadow = true
    end = [ "keyboard_layout", "tray", "recorder", "network", "bluetooth", "volume", "battery", "notifications" ]
    font_family = "Montserrat"
    font_weight = 700
    layer = "top"
    margin_ends = 200
    position = "bottom"
    radius = 10
    reserve_space = false
    shadow = true
    show_on_workspace_switch = false
    smart_auto_hide = true
    start = [ "launcher", "temp", "cpu", "ram", "network_rx" ]
    widget_spacing = 8

        [bar.default.dead_zone]
        command = "noctalia msg panel-toggle control-center"
        middle_command = "noctalia msg panel-toggle launcher"
        right_command = "noctalia msg panel-toggle session"

    [bar.workspaces]
    auto_hide = true
    background_opacity = 0.0
    capsule = true
    capsule_fill = "on_primary"
    capsule_opacity = 0.59999998658895493
    capsule_padding = 12.0
    capsule_radius = 12
    capsule_thickness = 0.83999998494982719
    center = [ "workspaces" ]
    contact_shadow = false
    enabled = true
    end = []
    font_family = "Montserrat"
    font_weight = 800
    margin_edge = 4
    margin_ends = 600
    margin_opposite_edge = 3
    position = "top"
    reserve_space = false
    shadow = false
    start = []
    thickness = 38

[control_center]
hidden_tabs = []
sidebar = "compact"
sidebar_section = "compact"

    [control_center.calendar]
    show_events_card = false

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

    [[control_center.shortcuts]]
    type = "power_profile"

    [[control_center.shortcuts]]
    type = "mic_mute"

[desktop_widgets]
schema_version = 1
widget_order = [ "desktop-widget-0000000000000002", "desktop-widget-0000000000000001", "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 144.0
    box_width = 256.0
    cx = 720.0
    cy = 661.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        color = "primary"
        format = "{:%H:%M}"

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 192.0
    box_width = 1440.0
    cx = 720.0
    cy = 96.0
    flip_y = true
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        bands = 96.0
        centered = false
        color_2 = "primary"
        mirrored = true
        show_when_idle = false

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 64.0
    box_width = 480.0
    cx = 727.5
    cy = 735.5
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = false
        color = "primary"
        format = "{: %d %b, %A}"

[dock]
active_monitor_only = true
auto_hide = true
enabled = false
launcher_position = "start"
position = "bottom"

[idle]
behavior_order = [ "lock", "screen-off" ]

    [idle.behavior.idle-behavior]
    action = "screen_off"
    enabled = true
    timeout = 900

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600

[location]
auto_locate = true

[lockscreen]
blur_intensity = 0.0
blurred_desktop = false
tint_intensity = 0.0

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 64.0
    box_width = 400.0
    cx = 720.0
    cy = 677.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.0
        background_radius = 0.0
        center_password_text = true
        input_opacity = 0.70000000000000007
        input_radius = 10.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 192.0
    box_width = 320.0
    cx = 720.0
    cy = 229.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        color = "primary"
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 368.0
    box_width = 1440.0
    cx = 720.0
    cy = 0.0
    output = "eDP-1"
    rotation = 0.0
    type = "audio_visualizer"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        bands = 68.0
        show_when_idle = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 80.0
    box_width = 560.0
    cx = 720.0
    cy = 309.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        color = "primary"
        format = "{:%d %b, %A}"
        shadow = true

[notification]
offset_y = 20
position = "bottom_right"
scale = 1.1000000089406967

[osd]
offset_y = 56
orientation = "horizontal"
position = "bottom_center"
scale = 1.4000000134110451

    [osd.kinds]
    media = false

[plugin_settings."noctalia/notes"]
notes_dir = "~/notes"

[plugin_settings."noctalia/screen_recorder"]
video_source = "focused"

[plugins]
enabled = [ "noctalia/screen_recorder", "noctalia/wallhaven", "noctalia/timer", "noctalia/translator" ]

    [[plugins.source]]
    auto_update = true
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    auto_update = true
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
clipboard_confirm_clear_history = true
clipboard_history_max_entries = 1000
clipboard_image_action_command = "satty --early-exit copy  --copy-command wl-copy -f -"
font_family = "Montserrat Medium"
launch_apps_as_systemd_services = true
offline_mode = false
password_style = "random"
polkit_agent = true
settings_show_advanced = true
telemetry_enabled = false

    [shell.launcher]
    app_grid = false
    compact = false
    session_search = true

    [shell.panel]
    borders = false
    clipboard_placement = "attached"
    launcher_placement = "attached"
    open_near_click_control_center = true
    polkit_placement = "attached"
    shadow = true
    transparency_mode = "soft"

    [shell.screenshot]
    confirm_region = false
    directory = "/home/alex/Pictures/Screenshots"
    pipe_command = "satty --early-exit copy  --copy-command wl-copy -f -"
    pipe_to_command = true
    save_to_file = true

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "q"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "e"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "s"
    variant = "destructive"

[theme]
builtin = "Tokyo-Night"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "faithful"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "qt" ]
    community_ids = [ "papirus-icons" ]

[wallpaper]
directory = "/home/alex/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/alex/Pictures/Wallpapers/wallhaven_n65epw.jpg"

    [wallpaper.last]
    path = "/home/alex/Pictures/Wallpapers/wallhaven_n65epw.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/alex/Pictures/Wallpapers/wallhaven_n65epw.jpg"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/alex/Pictures/Wallpapers/wallhaven-x8ye3z.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "faithful"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/alex/Pictures/Wallpapers/wallhaven_0j8o75.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-content"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/alex/Pictures/Wallpapers/wallhaven_7j96qv.jpg"
    theme_mode = "auto"
    wallpaper_scheme = "faithful"

    [[wallpaper.favorite]]
    path = "/home/alex/Pictures/Wallpapers/wallhaven_4d38m0.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    palette_source = "wallpaper"
    path = "/home/alex/Pictures/Wallpapers/wallhaven_n65epw.jpg"
    theme_mode = "dark"
    wallpaper_scheme = "m3-monochrome"

[widget.audio_visualizer]
bands = 30
scale = 1.5
width = 400.0

[widget.battery]
show_label = false

[widget.clock]
font_family = "DejaVu Sans"
font_weight = 700

[widget.control-center]
glyph = "rosette-filled"

[widget.cpu]
display = "text"

[widget.keyboard_layout]
show_icon = false

[widget.media]
art_size = 17.0
hide_when_no_media = true
title_scroll = "always"

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.network]
show_label = false

[widget.network_rx]
display = "text"

[widget.notes]
type = "noctalia/notes:notes"

[widget.ram]
display = "text"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.taskbar]
inactive_opacity = 0.84999999999999998

[widget.temp]
show_label = false

[widget.tray]
drawer = true
match_adjacent_spacing = true
pinned = [ "AmneziaVPN", "Discord", "steam", "TelegramDesktop" ]

[widget.volume]
show_label = false

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.workspaces]
minimal = false