{ lib, ... }: {
  # this is a mock file for the base template, for real need to be generated by nixos-generate-config
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/THIS-IS-MOCK-UUID";
    fsType = "ext4";
  };
}
